version: "3.8"
services:
  db_person:
    image: postgres:alpine
    container_name: person_db
    environment:
      POSTGRES_DB: "person_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/person"
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - db_person:/var/lib/postgresql/person
    ports:
      - "5478:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d person_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
volumes:
  db_person:
